# Generated by Django 3.2.4 on 2022-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='rentable',
            field=models.BooleanField(default=True),
        ),
    ]
