# Generated by Django 3.2.4 on 2021-07-20 12:17

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sale_productpriceadjustment_deal'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpriceadjustment',
            old_name='rentals',
            new_name='products',
        ),
        migrations.AddField(
            model_name='productrental',
            name='rental_products',
            field=models.ForeignKey(default=1, on_delete=models.SET(products.models.get_sentinel_product), related_name='rental_product', to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
