# Generated by Django 3.2.4 on 2021-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210720_0725'),
        ('rentals', '0002_rentalpriceadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpriceadjustment',
            name='rentals',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
