# Generated by Django 3.2.4 on 2022-03-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20220325_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalfulfilment',
            old_name='rental_base_price',
            new_name='unfulfilled_rental_price',
        ),
    ]
