# Generated by Django 3.2.4 on 2021-07-20 12:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_purchasing_type'),
        ('rentals', '0003_rename_rental_products_productrental_product_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrental',
            name='product_rented',
        ),
        migrations.AddField(
            model_name='productrental',
            name='rental_product',
            field=models.ForeignKey(default=1, on_delete=models.SET(products.models.get_sentinel_product), related_name='product_rental', to='products.product'),
            preserve_default=False,
        ),
    ]
