# Generated by Django 3.2.4 on 2021-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20210720_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrental',
            name='rental',
            field=models.BooleanField(default=True),
        ),
    ]
