# Generated by Django 3.2.4 on 2022-03-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_rental_base_price_rentalfulfilment_unfulfilled_rental_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalfulfilment',
            old_name='rental_end_inc_turnaround',
            new_name='_rental_end_inc_turnaround',
        ),
    ]
