# Generated by Django 3.2.4 on 2022-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rename_rental_end_inc_turnaround_rentalfulfilment__rental_end_inc_turnaround'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalfulfilment',
            old_name='unfulfilled_rental_price',
            new_name='_unfulfilled_rental_price',
        ),
    ]
