# Generated by Django 3.2.4 on 2021-07-21 13:28

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210721_1328'),
        ('rentals', '0006_remove_productrental_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFulfilment',
            fields=[
                ('productfulfilment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productfulfilment')),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('rental_price', models.IntegerField()),
                ('rental_fulfilled_product', models.ForeignKey(on_delete=models.SET(products.models.get_sentinel_product), related_name='fulfilled_product', to='products.productfulfilment')),
            ],
            bases=('products.productfulfilment',),
        ),
        migrations.DeleteModel(
            name='ProductRental',
        ),
    ]
