# Generated by Django 3.2.4 on 2022-03-28 09:14

from django.db import migrations, models
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rename_unfulfilled_rental_price_rentalfulfilment__unfulfilled_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldriver',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentaldriver',
            name='licence_back',
            field=imageit.models.CropItImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rentaldriver',
            name='licence_front',
            field=imageit.models.CropItImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rentalfulfilment',
            name='_unfulfilled_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of the rental before applying rental adjustments', max_digits=10),
        ),
    ]
