# Generated by Django 3.2.4 on 2022-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20220328_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalfulfilment',
            name='_fulfilled_rental_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fulfilled rate for rental. (rate after adjustments) to be multiplied by duration', max_digits=10),
            preserve_default=False,
        ),
    ]
