# Generated by Django 3.2.4 on 2022-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rentaldriver_proof_of_address_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldriver',
            name='user',
        ),
    ]
