# Generated by Django 3.2.4 on 2021-07-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_remove_rentalproduct_product_ptr'),
        ('products', '0005_auto_20210721_1328'),
        ('vans', '0003_auto_20210722_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalProduct',
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
