# Generated by Django 3.2.4 on 2022-04-21 13:42

from django.db import migrations
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_remove_rentaldriver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldriver',
            name='proof_of_address_2',
            field=imageit.models.ScaleItImageField(blank=True, upload_to=''),
        ),
    ]
