# Generated by Django 3.2.4 on 2021-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20210722_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalfulfilment',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
