# Generated by Django 3.2.4 on 2022-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20220421_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldriver',
            name='first_name',
            field=models.CharField(default='bob', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentaldriver',
            name='last_name',
            field=models.CharField(default='smith', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentaldriver',
            name='status',
            field=models.CharField(choices=[('APP', 'Approved'), ('ARV', 'Awaiting Review'), ('ARQ', 'Action Required'), ('DND', 'Denied'), ('INC', 'Incomplete')], default='ARV', max_length=3),
        ),
    ]
