# Generated by Django 3.2.4 on 2022-03-12 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_rentalfulfilment_rental_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalfulfilment',
            name='rental_user',
        ),
        migrations.AddField(
            model_name='rentalfulfilment',
            name='rental_end_inc_turnaround',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
