# Generated by Django 3.2.4 on 2022-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_rentaldriver_licence_check_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalfulfilment',
            name='status',
            field=models.CharField(choices=[('CNF', 'Confirmed'), ('PND', 'Pending'), ('DND', 'Denied'), ('CMP', 'Completed')], default='PND', max_length=3),
        ),
    ]
