# Generated by Django 3.2.4 on 2022-03-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220312_1057'),
        ('rentals', '0014_auto_20220312_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalExtra',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='rentalfulfilment',
            name='rental_extras',
            field=models.ManyToManyField(to='rentals.RentalExtra'),
        ),
    ]
