# Generated by Django 3.2.4 on 2022-03-12 11:59

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0015_auto_20220312_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField()),
                ('licence_front', imageit.models.CropItImageField(upload_to='')),
                ('licence_back', imageit.models.CropItImageField(upload_to='')),
                ('rental_fulfilment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentalfulfilment')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
