# Generated by Django 3.2.4 on 2022-04-23 03:10

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_alter_rentalfulfilment_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalfulfilment',
            name='pickup_location',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, help_text='Leave blank if not required', map_id='map', null=True),
        ),
    ]
