# Generated by Django 3.2.13 on 2022-04-27 11:39

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_auto_20220423_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldriver',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalfulfilment',
            name='pickup_location',
            field=mapbox_location_field.models.LocationField(blank=True, help_text='Leave blank if not required', map_attrs={'center': [-3.188512, 55.95348], 'placeholder': 'Search'}, null=True),
        ),
    ]
