# Generated by Django 3.2.4 on 2022-01-05 11:34

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220105_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='series',
            field=models.ManyToManyField(to='blogs.Series'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tag'),
        ),
    ]
