# Generated by Django 3.2.4 on 2022-01-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20220105_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='series',
        ),
        migrations.AddField(
            model_name='blog',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.series'),
        ),
    ]
