# Generated by Django 3.2.4 on 2022-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate', max_length=150, unique=True),
        ),
    ]
