# Generated by Django 3.2.4 on 2022-03-24 10:45

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import imageit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('avatar', imageit.models.CropItImageField(blank=True, max_height=300, max_width=300, null=True, quality=90, upload_to=accounts.models.UserProfile.get_upload_path, upscale=False)),
            ],
        ),
    ]
