# Generated by Django 3.2.4 on 2021-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('adj_type', models.CharField(choices=[('PER', '%'), ('DOL', '$')], default='PER', max_length=3)),
                ('adj_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
