# Generated by Django 3.2.4 on 2021-07-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceadjustment',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
