# Generated by Django 3.2.4 on 2021-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_priceadjustment_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceadjustment',
            name='sale',
        ),
        migrations.AlterField(
            model_name='priceadjustment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
