# Generated by Django 3.2.4 on 2021-07-08 14:19

from django.db import migrations, models
import django.db.models.deletion
import imageit.models
import vans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('registration', models.CharField(max_length=10)),
                ('odo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VanPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imageit.models.ScaleItImageField(upload_to=vans.models.VanPhotos.get_upload_path)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
            ],
        ),
    ]
