# Generated by Django 3.2.4 on 2021-07-20 11:44

from django.db import migrations, models
import django.db.models.deletion
import imageit.models
import vans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('registration', models.CharField(max_length=10)),
                ('odo', models.IntegerField(default=0)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='VanPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imageit.models.ScaleItImageField(upload_to=vans.models.VanPhotos.get_upload_path)),
                ('banner', models.BooleanField(default=False)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
            ],
        ),
    ]
