# Generated by Django 3.2.4 on 2022-03-24 10:45

from django.db import migrations, models
import django.db.models.deletion
import imageit.models
import vans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('rentalproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.rentalproduct')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('sleeps', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('drive_type', models.CharField(choices=[('4x4', '4x4'), ('2x4', '2x4')], max_length=3)),
                ('pets', models.BooleanField(default=True)),
                ('registration', models.CharField(max_length=10)),
                ('odo', models.IntegerField(default=0)),
            ],
            bases=('rentals.rentalproduct',),
        ),
        migrations.CreateModel(
            name='VanPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imageit.models.ScaleItImageField(upload_to=vans.models.VanPhotos.get_upload_path)),
                ('banner', models.BooleanField(default=False)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
            ],
        ),
    ]
