# Generated by Django 3.2.4 on 2021-07-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='van',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vanphotos',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='van',
            name='odo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='van',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
