# Generated by Django 3.2.4 on 2021-07-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rentalproduct'),
        ('vans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='van',
            name='rentalproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.rentalproduct'),
            preserve_default=False,
        ),
    ]
