# Generated by Django 3.2.4 on 2021-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0002_auto_20210717_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='van',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='van',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
