# Generated by Django 3.2.4 on 2021-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0003_auto_20210722_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='make',
            field=models.CharField(default='Citroen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='model',
            field=models.CharField(default='Relay', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='sleeps',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
