# Generated by Django 3.2.4 on 2021-07-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vans', '0003_auto_20210717_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='available',
        ),
        migrations.RemoveField(
            model_name='van',
            name='description',
        ),
        migrations.RemoveField(
            model_name='van',
            name='id',
        ),
        migrations.RemoveField(
            model_name='van',
            name='name',
        ),
        migrations.RemoveField(
            model_name='van',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='van',
            name='slug',
        ),
        migrations.AddField(
            model_name='van',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product'),
            preserve_default=False,
        ),
    ]
