# Generated by Django 3.2.4 on 2021-10-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0004_auto_20210725_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='drive_type',
            field=models.CharField(choices=[('4x4', '4x4'), ('4x4', '4x4')], default='2x4', max_length=3),
            preserve_default=False,
        ),
    ]
