# Generated by Django 3.2.4 on 2021-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0005_van_drive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='pets',
            field=models.BooleanField(default=True),
        ),
    ]
