# Generated by Django 3.2.4 on 2021-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0006_van_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='drive_type',
            field=models.CharField(choices=[('4x4', '4x4'), ('2x4', '2x4')], max_length=3),
        ),
    ]
