# This is a basic workflow to help you get started with Actions

name: Test, Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DJANGO_DEBUG: '0'
  DJANGO_ALLOWED_HOSTS: ''
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  EMAIL_USER: ''
  EMAIL_PASSWORD: ''
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        include:
          - python-version: 3.9
            django-version: Django==3.2

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ${{ matrix.django-version }}
      - name: Test Django=${{ matrix.django-version }}, Python=${{ matrix.python-version }}
        run: |
          python manage.py test --noinput

  # Build job to build static files
  build_and_deploy_static:
    # Dependant on test passing
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Node dependancies
        run: npm ci
      - name: Node build
        run: npm run build --if-present -- --no-watch
      - name: Node test
        run: npm test
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependancies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Collect static
        run: |
          python manage.py collectstatic --noinput
  
        
  # Job to deploy python files to server
  deploy_to_server:
    # Dependant on test passing
    needs: build_and_deploy_static
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependancies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      #Be Careful automatically applying migrations to prod databases.
      - name: Make migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
        
      # Retreive private key from secrets and save as file deployment.key
      - name: Create identity file
        env:
          DEPLOYMENT_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$DEPLOYMENT_SSH_KEY" | base64 --decode  >deployment.key
          chmod 400 deployment.key
      
      # Run update scripts on remote server
      - name: Update Application on production server
        run: |
          ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} touch ~/heyyyyy
          ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} if ! git ls-remote origin --quiet; then git -C /srv/bdc-venv/src remote add origin git@github.com-bdc:scott-j5/bdc.git; fi
          ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} git -C /srv/bdc-venv/src fetch --all
          ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} git -C /srv/bdc-venv/src reset --hard "${GITHUB_SHA}"
        # ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} git -C /srv/bdc-venv/src clone git@github.com-bdc:scott-j5/bdc.git .
        # ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} git -C /srv/bdc-venv/src checkout "${GITHUB_SHA}"
        # set perms
        # ssh -i deployment.key deploy@${{ secrets.SERVER_IP }} sudo /home/ubuntu/thumbsup/admin/update.bash

        