# Generated by Django 3.2.4 on 2021-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('adj_type', models.CharField(choices=[('PER', '%'), ('DOL', '$')], default='PER', max_length=3)),
                ('adj_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('base_price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
