# Generated by Django 3.2.4 on 2021-07-19 12:57

import core.models
from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceadjustment',
            old_name='end',
            new_name='period_end',
        ),
        migrations.RenameField(
            model_name='priceadjustment',
            old_name='start',
            new_name='period_start',
        ),
        migrations.AddField(
            model_name='priceadjustment',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0, help_text='Rates are calculated and charged hourly!'),
        ),
        migrations.CreateModel(
            name='ProductReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateTimeField()),
                ('reservation_end', models.DateTimeField()),
                ('reservation_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=models.SET(products.models.get_sentinel_product), to='products.product')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
