# Generated by Django 3.2.4 on 2021-07-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpriceadjustment',
            old_name='sale',
            new_name='deal',
        ),
    ]
