# Generated by Django 3.2.4 on 2022-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_rentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='On Rentable items price is the equivelant daily rate before adjustments!', max_digits=10, verbose_name='Price'),
        ),
    ]
