# Generated by Django 3.2.4 on 2021-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210719_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rentable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0, help_text='On rentable items, rates are calculated and charged hourly!'),
        ),
        migrations.DeleteModel(
            name='ProductReservation',
        ),
    ]
