# Generated by Django 3.2.4 on 2021-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_purchasing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_purchasing_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RENTAL', 'Rental'), ('PRODUCT', 'Product')], default='PRODUCT', max_length=10),
        ),
    ]
