# Generated by Django 3.2.4 on 2021-07-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('products', '0003_auto_20210719_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceAdjustment',
            fields=[
                ('priceadjustment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoicing.priceadjustment')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            bases=('invoicing.priceadjustment',),
        ),
        migrations.DeleteModel(
            name='PriceAdjustment',
        ),
    ]
