# Generated by Django 3.2.4 on 2021-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210720_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpriceadjustment',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productpriceadjustment',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
