# Generated by Django 3.2.4 on 2021-07-22 13:24

from django.db import migrations, models
import django.db.models.deletion
import imageit.models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210721_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imageit.models.ScaleItImageField(max_height=1500, max_width=1500, quality=100, upload_to=products.models.ProductImage.get_upload_path, upscale=False)),
                ('banner', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
