# Generated by Django 3.2.4 on 2022-04-21 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfulfilment',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
