# Generated by Django 3.2.4 on 2021-07-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='photo',
            new_name='image',
        ),
    ]
