# Generated by Django 3.2.4 on 2021-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_photo_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfulfilment',
            old_name='product_base_price',
            new_name='fulfilled_price',
        ),
        migrations.AddField(
            model_name='productfulfilment',
            name='fulfilled_product_base_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
