# Generated by Django 3.2.13 on 2024-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
