# Generated by Django 3.2.4 on 2021-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210725_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='On rentable items, rates are calculated and charged hourly!', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productfulfilment',
            name='fulfilled_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productfulfilment',
            name='fulfilled_product_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
