# Generated by Django 3.2.4 on 2021-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='banner',
            field=models.BooleanField(default=False, help_text='Banner images should be in a landscape format for best results'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.BooleanField(default=False, help_text='Thumbnail photo dimensions should be square for best results'),
        ),
    ]
