# Generated by Django 3.2.4 on 2021-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Url appropriate characters only, no spaces', unique=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Search Bootstrap icons, Feather Icons or Font awesome icons for available class names.', max_length=100),
        ),
    ]
