# Generated by Django 3.2.4 on 2022-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211026_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
