# Generated by Django 3.2.4 on 2022-03-12 04:07

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_productfeature_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_turnaround',
            field=models.IntegerField(blank=True, default=1, help_text='RENTALS ONLY: Minimum time between return and re-rental in Hours', null=True),
        ),
        migrations.AddField(
            model_name='productfulfilment',
            name='fulfilling_user',
            field=models.ForeignKey(default=1, on_delete=models.SET(core.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
    ]
