# Generated by Django 3.2.4 on 2022-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220312_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.ProductFeature'),
        ),
    ]
